module.exports.locales = function(){
    return [
        { code : 'en-AS', name : 'American Samoa' },
        { code : 'en-AG', name : 'Antigua & Barbuda' },
        { code : 'en-AI', name : 'Anguilla' },
        { code : 'en-AT', name : 'Austria' },
        { code : 'en-AU', name : 'Australia' },
        { code : 'en-BB', name : 'Barbados' },
        { code : 'en-BE', name : 'Belgium' },
        { code : 'en-BI', name : 'Burundi' },
        { code : 'en-BM', name : 'Bermuda' },
        { code : 'en-BS', name : 'Bahamas' },
        { code : 'en-BW', name : 'Botswana' },
        { code : 'en-BZ', name : 'Belize' },
        { code : 'en-CA', name : 'Canada' },
        { code : 'en-CC', name : 'Cocos [Keeling] Islands' },
        { code : 'en-CK', name : 'Cook Islands' },
        { code : 'en-CM', name : 'Cameroon' },
        { code : 'en-CX', name : 'Christmas Island' },
        { code : 'en-CY', name : 'Cyprus' },
        { code : 'en-DE', name : 'Germany' },
        { code : 'en-DG', name : 'Diego Garcia' },
        { code : 'en-DK', name : 'Denmark' },
        { code : 'en-DM', name : 'Dominica' },
        { code : 'en-ER', name : 'Eritrea' },
        { code : 'en-FI', name : 'Finland' },
        { code : 'en-FJ', name : 'Fiji' },
        { code : 'en-FK', name : 'Falkland Islands' },
        { code : 'en-FM', name : 'Micronesia' },
        { code : 'en-GB', name : 'United Kingdom' },
        { code : 'en-US', name : 'United States' },
        { code : 'en-GD', name : 'Grenada' },
        { code : 'en-GG', name : 'Guernsey' },
        { code : 'en-GH', name : 'Ghana' },
        { code : 'en-GI', name : 'Gibraltar' },
        { code : 'en-GM', name : 'Gambia' },
        { code : 'en-GU', name : 'Guam' },
        { code : 'en-GY', name : 'Guyana' },
        { code : 'en-HK', name : 'Hong Kong SAR China' },
        { code : 'en-IE', name : 'Ireland' },
        { code : 'en-IL', name : 'Israel' },
        { code : 'en-IM', name : 'Isle of Man' },
        { code : 'en-IN', name : 'India' },
        { code : 'en-IO', name : 'British Indian Ocean Territory' },
        { code : 'en-JE', name : 'Jersey' },
        { code : 'en-JM', name : 'Jamaica' },
        { code : 'en-KE', name : 'Kenya' },
        { code : 'en-KI', name : 'Kiribati' },
        { code : 'en-KN', name : 'St. Kitts & Nevis' },
        { code : 'en-KY', name : 'Cayman Islands' },
        { code : 'en-LC', name : 'St. Lucia' },
        { code : 'en-LR', name : 'Liberia' },
        { code : 'en-LS', name : 'Lesotho' },
        { code : 'en-MG', name : 'Madagascar' },
        { code : 'en-MH', name : 'Marshall Islands' },
        { code : 'en-MO', name : 'Macau SAR China' },
        { code : 'en-MP', name : 'Northern Mariana Islands' },
        { code : 'en-MS', name : 'Montserrat' },
        { code : 'en-MT', name : 'Malta' },
        { code : 'en-MU', name : 'Mauritius' },
        { code : 'en-MW', name : 'Malawi' },
        { code : 'en-MY', name : 'Malaysia' },
        { code : 'en-NA', name : 'Namibia' },
        { code : 'en-NF', name : 'Norfolk Island' },
        { code : 'en-NG', name : 'Nigeria' },
        { code : 'en-NL', name : 'Netherlands' },
        { code : 'en-NR', name : 'Nauru' },
        { code : 'en-NU', name : 'Niue' },
        { code : 'en-NZ', name : 'New Zealand' },
        { code : 'en-PG', name : 'Papua New Guinea' },
        { code : 'en-PH', name : 'Philippines' },
        { code : 'en-PK', name : 'Pakistan' },
        { code : 'en-PN', name : 'Pitcairn Islands' },
        { code : 'en-PR', name : 'Puerto Rico' },
        { code : 'en-PW', name : 'Palau' },
        { code : 'en-RW', name : 'Rwanda' },
        { code : 'en-SB', name : 'Solomon Islands' },
        { code : 'en-SC', name : 'Seychelles' },
        { code : 'en-SD', name : 'Sudan' },
        { code : 'en-SE', name : 'Sweden' },
        { code : 'en-CH', name : 'Switzerland' },
        { code : 'en-SG', name : 'Singapore' },
        { code : 'en-SH', name : 'St. Helena' },
        { code : 'en-SI', name : 'Slovenia' },
        { code : 'en-SL', name : 'Sierra Leone' },
        { code : 'en-SS', name : 'South Sudan' },
        { code : 'en-SX', name : 'Sint Maarten' },
        { code : 'en-SZ', name : 'Swaziland' },
        { code : 'en-TC', name : 'Turks & Caicos Islands' },
        { code : 'en-TK', name : 'Tokelau' },
        { code : 'en-TO', name : 'Tonga' },
        { code : 'en-TT', name : 'Trinidad & Tobago' },
        { code : 'en-TV', name : 'Tuvalu' },
        { code : 'en-TZ', name : 'Tanzania' },
        { code : 'en-UG', name : 'Uganda' },
        { code : 'en-UM', name : 'U.S. Outlying Islands' },
        { code : 'en-VC', name : 'St. Vincent & Grenadines' },
        { code : 'en-VG', name : 'British Virgin Islands' },
        { code : 'en-VI', name : 'U.S. Virgin Islands' },
        { code : 'en-VU', name : 'Vanuatu' },
        { code : 'en-WS', name : 'Samoa' },
        { code : 'en-ZA', name : 'South Africa' },
        { code : 'en-ZM', name : 'Zambia' },
        { code : 'en-ZW', name : 'Zimbabwe' },
    ];    
}